disks:
  mini:
    disk: disk7
    mounts:
      - path: /opt
        volume: opt
      - path: /Users/moonlight/Workspace
        volume: Workspace
      - path: /Users/moonlight/.ssh
        volume: ssh
      - path: /Users/moonlight/.config
        volume: config
      - path: /Users/moonlight/.aws
        volume: aws
      - path: /Users/moonlight/.gnupg
        volume: gnupg
      - path: /Users/moonlight/.kube
        volume: kube
      - path: /Users/moonlight/.cargo
        volume: cargo
      - path: /Users/moonlight/.npm
        volume: npm
      - path: /Users/moonlight/.rustup
        volume: rustup
      - path: /Users/moonlight/.vscode
        volume: vscode
  azmb:
    disk: disk3
    mounts:
      - path: /opt
        volume: opt
      - path: /Users/moonlight/Workspace
        volume: Workspace
      - path: /Users/moonlight/.ssh
        volume: ssh
      - path: /Users/moonlight/.config
        volume: config

# Linux
apt_packages:
  - zsh
  - open-iscsi
  - flatpak
  - plasma-discover-backend-flatpak

  # Podman
  - uidmap
  - podman
  # Python deps
  - build-essential
  - zlib1g-dev
  - libncurses5-dev
  - libgdbm-dev
  - libnss3-dev
  - libssl-dev
  - libreadline-dev
  - libffi-dev
  - libbz2-dev
  - liblzma-dev
  - libsqlite3-dev
  - tk-dev
  - uuid-dev

  # Ruby deps
  - libyaml-dev
