[tools]
node = "24.11.0"
ruby = "3.4.4"
python = "3.14.0"
golang = "1.25.0"
rust = "1.93.1"
pnpm = "10.18.0"
opentofu = "1.11.3"
terraform = "1.14.3"
terragrunt = "0.97.2"
java = "openjdk-21"

[settings]
python.default_packages_file = "$HOME/.config/mise/.default-python-packages"
